[package]
name = "futures-concurrency"
version = "7.4.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yoshuawuyts/futures-concurrency"
documentation = "https://docs.rs/futures-concurrency"
description = "Structured concurrency operations for async Rust"
readme = "README.md"
edition = "2021"
keywords = []
categories = []
authors = [
    "Yoshua Wuyts <yoshuawuyts@gmail.com>"
]

[profile.bench]
debug = true

[lib]
bench = false

[[bench]]
name = "bench"
harness = false

[[bench]]
name = "compare"
harness = false

[dependencies]
bitvec = { version = "1.0.1", default-features = false, features = ["alloc"] }
futures-core = "0.3"
pin-project = "1.0.8"
slab = "0.4.8"
smallvec = "1.11.0"

[dev-dependencies]
futures = "0.3.25"
futures-lite = "1.12.0"
criterion = { version = "0.3", features = ["async", "async_futures", "html_reports"] }
async-std = { version = "1.12.0", features = ["attributes"] }
futures-time = "3.0.0"
lending-stream = "1.0.0"
rand = "0.8.5"
